Han 139: Agregar servicio de autenticacion
Hanagotchi/plants pull request #20
Opened 2024-06-03 15:23 UTC by feijooso

## Linked ticket in Jira
- https://hanagotchi.atlassian.net/jira/software/projects/HAN/boards/1?selectedIssue=HAN-139

## Describe your changes, marking the new features and possible risks
- Se agrega servicio de autenticacion que valida que el usuario autenticado tenga permisos para relizar esa accion. 

## Media: upload photos or videos (if needed)
-

2024-06-18 21:08 UTC, Agustinefe requested changes
A modo de comentarios:

Los endpoints de Create Plant y Get Logs By User estan recibiendo aun el id del usuario, junto con el access token, lo cual hace el ingreso manual de un user_id algo redundante. Podrian quitarse e inferir el user_id desde el access token.

De todas formas el chequeo de los ids matcheen se hace, asi que cumple con su objetivo de añadir la capa de seguridad a los endpoints. Debido a esto, quizas no priorizaria un cambio de este estilo, pero si tenes ganas, go ahead.

Tal vez modificar estos endpoints pueda tener impacto en la app, por lo que una vez mergeado tendriamos que estar atentos a que todo funcione bien en las pruebas basales.

2024-06-18 21:08 UTC, Agustinefe commented on app/main.py
> +        return await plants_controller.handle_get_plants_by_user(id_user, limit, token)
Si le paso un id_user, chequea que el id coincida con el que contiene encriptado el access token, de manera que si le paso un id que no es mio, no puedo obtener las plantas de ese id.

Pero si no le paso nada, me fetchea las plantas de todos los usuarios.

Creo que lo ideal es que no le pasemos un id_user, y que infiera este desde el token, para que siempre devuelva las plantas del requestor.

2024-06-21 03:23 UTC, feijooso commented on app/main.py
> +        return await plants_controller.handle_get_plants_by_user(id_user, limit, token)
para eso borramos el get all, no? o sea dejo solo un endpoint para buscar segun el token y listo, deja de existir un get all

2024-06-21 03:24 UTC, Agustinefe commented on app/main.py
> +        return await plants_controller.handle_get_plants_by_user(id_user, limit, token)
Adhiero. Volemos el get_all

2024-06-21 04:01 UTC, feijooso commented on app/main.py
> +        return await plants_controller.handle_get_plants_by_user(id_user, limit, token)
modificado

2024-06-21 14:15 UTC, Agustinefe approved these changes
LGTM 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

2024-06-21 14:42 UTC, Agustinefe commented
Faltaba una / en todos los endpoints del external service de user, y hacia que rompiese heroku

2024-06-21 16:03 UTC, merged