HAN-46: Editar una bitacora ya existente
Hanagotchi/plants pull request #7
Opened 2024-02-19 21:07 UTC by fjpacheco

## Linked ticket in Jira
- https://hanagotchi.atlassian.net/jira/software/projects/HAN/boards/1/backlog

## Describe your changes, marking the new features and possible risks
- Se agregó endpoint PAtCH para permitir editar el titulo, contenido y plant_id de una bitacora existente.
- Para agregar o borrar nueva foto de una bitacora: viendo que existe una tabla de logs_photos, pienso que lo mejor seria crear 2 nuevos endpoints para agregar nueva foto dado un id o url de foto, o para eliminar una foto existente de una bitacora. [DEBATIR EN WEEKLY]

## Dependencias

- Se necesita #6 revisado y mergeado ya que se partió de dicha rama.

2024-02-20 23:12 UTC, Agustinefe commented
Veo que hay un problema por algo del HAN-44. Ya esta arreglado, asi que mergealo cuando quieras asi puedo revisarte este PR.

2024-02-22 20:45 UTC, Agustinefe commented
Pushee un mini fix de algo que no se si es mio o tuyo (sospecho que mio). El post estaba fallando porque el model de plantas estaba referenciando mal el nombre cientifico de la tabla de tipos de plantas.

2024-02-22 20:52 UTC, Agustinefe requested changes

2024-02-22 20:52 UTC, Agustinefe commented on app/database/database.py
> +        self.session.commit()
Recorda que existe la funcion UPDATE para actualizar rows: https://docs.sqlalchemy.org/en/20/tutorial/data_update.html

2024-02-22 22:18 UTC, fjpacheco commented on app/database/database.py
> +        self.session.commit()
agregado, pero no logre evitar el if

adiciono retorno de true/false que ayuda para saber si vino todos los campos del scheme vacios

2024-02-22 22:32 UTC, Agustinefe approved these changes
Adelante reyy

2024-02-22 22:46 UTC, merged